{"trial_id": "002", "hyperparameters": {"space": [{"class_name": "Fixed", "config": {"name": "code_size", "conditions": [], "value": 32}}, {"class_name": "Fixed", "config": {"name": "activation", "conditions": [], "value": "tanh"}}, {"class_name": "Fixed", "config": {"name": "n_layers", "conditions": [], "value": 1}}, {"class_name": "Fixed", "config": {"name": "n_units", "conditions": [], "value": 16}}, {"class_name": "Fixed", "config": {"name": "kernel_size", "conditions": [], "value": 100}}, {"class_name": "Fixed", "config": {"name": "max_pooling", "conditions": [], "value": 2}}, {"class_name": "Fixed", "config": {"name": "batch_norm", "conditions": [], "value": false}}, {"class_name": "Fixed", "config": {"name": "dropout", "conditions": [], "value": 0.0}}, {"class_name": "Fixed", "config": {"name": "learning_rate", "conditions": [], "value": 0.001}}, {"class_name": "Choice", "config": {"name": "strides", "default": 25, "conditions": [], "values": [10, 25, 50], "ordered": true}}], "values": {"code_size": 32, "activation": "tanh", "n_layers": 1, "n_units": 16, "kernel_size": 100, "max_pooling": 2, "batch_norm": false, "dropout": 0.0, "learning_rate": 0.001, "strides": 50}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 235, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 287, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 214, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras_tuner\\engine\\hypermodel.py\", line 144, in fit\n    return model.fit(*args, **kwargs)\n  File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\latta\\AppData\\Roaming\\Python\\Python310\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 52, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node 'SquaredDifference' defined at (most recent call last):\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 992, in launch_instance\n      app.start()\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 711, in start\n      self.io_loop.start()\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n      self.asyncio_loop.run_forever()\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\asyncio\\base_events.py\", line 1906, in _run_once\n      handle._run()\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\asyncio\\events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n      await self.process_one()\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n      await dispatch(*args)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n      await result\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n      reply_content = await reply_content\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 411, in do_execute\n      res = shell.run_cell(\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 531, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2961, in run_cell\n      result = self._run_cell(\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3016, in _run_cell\n      result = runner(coro)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3221, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3400, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3460, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"C:\\Users\\latta\\AppData\\Local\\Temp\\ipykernel_2440\\2717154168.py\", line 77, in <module>\n      tuner.search(train_small, validation_data = val_small,\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 230, in search\n      self._try_run_and_update_trial(trial, *fit_args, **fit_kwargs)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 270, in _try_run_and_update_trial\n      self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 235, in _run_and_update_trial\n      results = self.run_trial(trial, *fit_args, **fit_kwargs)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 287, in run_trial\n      obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 214, in _build_and_fit_model\n      results = self.hypermodel.fit(hp, model, *args, **kwargs)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras_tuner\\engine\\hypermodel.py\", line 144, in fit\n      return model.fit(*args, **kwargs)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1564, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1160, in train_function\n      return step_function(self, iterator)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1146, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1135, in run_step\n      outputs = model.train_step(data)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras\\engine\\training.py\", line 998, in train_step\n      return self.compute_metrics(x, y, y_pred, sample_weight)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1092, in compute_metrics\n      self.compiled_metrics.update_state(y, y_pred, sample_weight)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras\\engine\\compile_utils.py\", line 605, in update_state\n      metric_obj.update_state(y_t, y_p, sample_weight=mask)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras\\utils\\metrics_utils.py\", line 77, in decorated\n      update_op = update_state_fn(*args, **kwargs)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras\\metrics\\base_metric.py\", line 143, in update_state_fn\n      return ag_update_state(*args, **kwargs)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras\\metrics\\base_metric.py\", line 700, in update_state\n      matches = ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"c:\\Users\\latta\\miniconda3\\envs\\tensorf_env\\lib\\site-packages\\keras\\losses.py\", line 1486, in mean_squared_error\n      return backend.mean(tf.math.squared_difference(y_pred, y_true), axis=-1)\nNode: 'SquaredDifference'\nIncompatible shapes: [3,220500] vs. [3,220450]\n\t [[{{node SquaredDifference}}]] [Op:__inference_train_function_773044]\n"}